using Microsoft.Extensions.Options;

namespace HADesktopAgent.Core.Mqtt
{
    /// <summary>
    /// Reads <see cref="MqttConfiguration.PasswordFile"/> into
    /// <see cref="MqttConfiguration.Password"/> at startup.
    /// <para>
    /// The indirection exists so config.json can be generated by a configuration manager
    /// (nix, Ansible, a container image) without the broker password being part of it.
    /// The path is not a secret; the file it points at is, and its permissions are the
    /// secret store's business, not ours.
    /// </para>
    /// </summary>
    public class MqttSecretFileLoader : IPostConfigureOptions<MqttConfiguration>
    {
        public void PostConfigure(string? name, MqttConfiguration options)
        {
            if (string.IsNullOrWhiteSpace(options.PasswordFile))
            {
                return;
            }

            var path = options.PasswordFile.Trim();

            string contents;
            try
            {
                contents = File.ReadAllText(path);
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException(
                    $"MQTT PasswordFile '{path}' could not be read: {ex.Message}", ex);
            }

            // Only the trailing newline goes: `echo secret > file` and most secret stores add
            // one, but leading and inner whitespace could genuinely be part of a password.
            options.Password = contents.TrimEnd('\r', '\n');

            if (options.Password.Length == 0)
            {
                throw new InvalidOperationException($"MQTT PasswordFile '{path}' is empty");
            }
        }
    }
}
